arr = [1,2,3,4,5,7,8,9,10] # O(1)
print(arr)
arr.reverse() # O(n)
print(arr) 
arr.sort() # O(n logn)
print(arr)
print(arr[0]) # O(1)
print(arr[-1]) # O(1)
print(arr[3:5]) # O(1)
arr.insert(3, 10) # O(n)
print(arr)
arr.pop(4) # O(n)
arr.pop() # O(1)
print(arr)